[package]
name = "rsp"
version = "0.1.0"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
dotenv = "0.14"
postgres = { version = "0.15", features = ["with-chrono"] }
rand = "0.7"
regex = "1.2"
reqwest = { version = "0.9", features = ["socks"] }
select = "0.4"
